plugins {
  id 'java-library'
  id 'maven-publish'
}

apply from: "$rootDir/scripts/publish-maven.gradle"
apply from: 'publish.gradle'

version = ext['PUBLISH_VERSION']
description = ext['PUBLISH_DESCRIPTION']

java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8

  withSourcesJar()
  withJavadocJar()
}

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.hamcrest:hamcrest:2.2'
}

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
}

jar {
  enabled = true
}
